#!/usr/bin/env bash
# 'displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration, and displays Best School for the other iterations
export B=1
while [ $B -le 10 ]
do
	(( B++ ))
if [ $B -eq 5 ]
then
	echo 'bad luck'
elif [ $B -eq 9 ]
then
	echo 'good luck'
else
	echo "Best School"
fi
done
